
# Before on ibrah5em laptop:
# fitness:
#   accuracy_weight: 0.6727598960405373
#   interpretability_weight: 0.3272401039594627
# ga:
#   crossover_prob: 0.5646016151595842
#   mutation_prob: 0.25576213407723136
#   n_generations: 60
#   population_size: 130
#   tournament_size: 5
# tree:
#   max_depth: 6
#   min_samples_leaf: 8
#   min_samples_split: 16

# After Hyperparameters Tuning on Luf8y Laptop:

fitness:
  accuracy_weight: 0.8619364624278322
  interpretability_weight: 0.13806353757216783
ga:
  crossover_prob: 0.6733843409158413
  mutation_prob: 0.15297790351647228
  n_generations: 50
  population_size: 140
  tournament_size: 2
tree:
  max_depth: 6
  min_samples_leaf: 5
  min_samples_split: 18




